import type { FlowScenario } from './flowScenario'

export const sessionLoopLifecycleScenario: FlowScenario = {
  title: 'Session 主循环与返回分支',
  summary: '从 prompt.ts 创建消息与 processor，到流式事件处理、工具回写，再到 continue / compact / stop 三种返回路径。',
  lanes: [
    { id: 'entry', label: '消息入口' },
    { id: 'processor', label: 'processor.ts' },
    { id: 'llm', label: 'LLM Stream' },
    { id: 'parts', label: 'MessageV2 Parts' },
    { id: 'result', label: '返回分支' },
  ],
  steps: [
    {
      id: 'prompt',
      title: 'prompt.ts 建立本轮会话',
      detail: '创建 user / assistant 消息、加载 tools 和 system prompt，然后启动 SessionProcessor。',
      lane: 'entry',
      codeLabel: 'session/prompt.ts',
      emphasis: '这一章真正的入口不只是“多轮对话”，而是 user 消息如何进入 session 并启动处理循环。',
    },
    {
      id: 'processor',
      title: '创建 processor',
      detail: 'processor.ts 持有 toolcalls、snapshot、blocked、needsCompaction 等状态，准备进入主循环。',
      lane: 'processor',
      codeLabel: 'session/processor.ts',
    },
    {
      id: 'stream',
      title: '消费 fullStream',
      detail: '调用 LLM.stream 后按事件类型处理 text / reasoning / tool-call / finish-step 等流式片段。',
      lane: 'llm',
      codeLabel: 'session/llm.ts · fullStream',
    },
    {
      id: 'tool-call',
      title: '收到 tool-call',
      detail: '写入 ToolPart，执行工具，必要时触发权限确认；这一轮也会做 doom loop 检测。',
      lane: 'parts',
      codeLabel: 'MessageV2.ToolPart / PermissionNext.ask',
      kind: 'decision',
    },
    {
      id: 'tool-result',
      title: '结果回写 Parts',
      detail: '工具输出、文字增量和步骤边界都以 Part 形式持久化并广播给多端 UI。',
      lane: 'parts',
      codeLabel: 'MessageV2.ToolPart / updatePartDelta',
    },
    {
      id: 'decision',
      title: '决定返回值',
      detail: '每轮处理结束后，processor 根据 blocked 和 needsCompaction 决定返回 continue / compact / stop。',
      lane: 'processor',
      codeLabel: 'return "continue" | "compact" | "stop"',
      kind: 'decision',
    },
    {
      id: 'continue',
      title: 'continue',
      detail: '正常完成本轮，等待下一条用户消息或继续下一轮处理。',
      lane: 'result',
      kind: 'commit',
    },
    {
      id: 'compact',
      title: 'compact',
      detail: '上下文占用逼近上限时转入 SessionCompaction，压缩完成后再重新组装上下文继续。',
      lane: 'result',
      codeLabel: 'session/compaction.ts',
      kind: 'warning',
    },
    {
      id: 'stop',
      title: 'stop',
      detail: '权限拒绝、不可恢复错误，或 doom loop 触发用户介入时，本轮会话暂停等待处理。',
      lane: 'result',
      codeLabel: 'DOOM_LOOP_THRESHOLD / permission: "doom_loop"',
      kind: 'warning',
    },
  ],
  edges: [
    { from: 'prompt', to: 'processor' },
    { from: 'processor', to: 'stream' },
    { from: 'stream', to: 'tool-call', label: 'finish_reason = tool-calls' },
    { from: 'tool-call', to: 'tool-result' },
    { from: 'tool-result', to: 'decision' },
    { from: 'stream', to: 'decision', style: 'dashed', label: '文本流结束' },
    { from: 'decision', to: 'continue', label: '正常完成' },
    { from: 'decision', to: 'compact', label: 'needsCompaction' },
    { from: 'decision', to: 'stop', label: 'blocked / error / doom loop' },
    { from: 'compact', to: 'stream', style: 'dashed', label: '压缩后继续' },
  ],
}
